name: Deploy to EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to EC2 via SSH
              uses: appleboy/ssh-action@1.0.3
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                    cd ~/AI_Powered_Customer_Support_Agent
                    git pull origin main
                    source .venv/bin/activate
                    uv pip install -r requirements.txt
                    cat << EOF > .env
                    OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
                    OPENAI_BASE_URL=${{ secrets.OPENAI_BASE_URL }}
                    MONGODB_URL=${{ secrets.MONGODB_URL }}
                    OPENAI_MODEL_NAME=${{ secrets.OPENAI_MODEL_NAME }}
                    MEM0_API_KEY=${{ secrets.MEM0_API_KEY }}
                    EOF
                    sudo systemctl restart fastapi-app

